---
title: "Progra"
author: "SebastianFalvy"
format: html
editor: visual
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(moments)
df<-read_csv("wiki_movie_plots_deduped.csv")
```

```{r}
df
```

```{r}
print("Release year datos faltantes o nulos")
sum(is.na(df$`Release Year`))
print("Title datos faltantes o nulos")
sum(is.na(df$Title))
print("Origin/Ethnicity datos faltantes o nulos")
sum(is.na(df$`Origin/Ethnicity`))
print("Director datos faltantes o nulos")
sum(is.na(df$Director))
print("Cast datos faltantes o nulos")
sum(is.na(df$Cast))
print("Genre datos faltantes o nulos")
sum(is.na(df$Genre))
print("Wiki Page datos faltantes o nulos")
sum(is.na(df$`Wiki Page`))
print("Plot datos faltantes o nulos")
sum(is.na(df$Plot))
```

```{r}
df$Cast <- replace(df$Cast, is.na(df$Cast), "Unknown")
df$Genre <- replace(df$Genre, is.na(df$Genre), "Unknown")
df$Genre <- replace(df$Genre, df$Genre=="Unknown", "unknown")
df$Director <- replace(df$Director, df$Director=="Unknown", "unknown")
df
```

```{r}
print("Release year datos faltantes o nulos")
sum(is.na(df$`Release Year`))
print("Title datos faltantes o nulos")
sum(is.na(df$Title))
print("Origin/Ethnicity datos faltantes o nulos")
sum(is.na(df$`Origin/Ethnicity`))
print("Director datos faltantes o nulos")
sum(is.na(df$Director))
print("Cast datos faltantes o nulos")
sum(is.na(df$Cast))
print("Genre datos faltantes o nulos")
sum(is.na(df$Genre))
print("Wiki Page datos faltantes o nulos")
sum(is.na(df$`Wiki Page`))
print("Plot datos faltantes o nulos")
sum(is.na(df$Plot))
```
